# Generated by Django 4.2 on 2023-05-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="min_distance",
            field=models.FloatField(null=True, verbose_name="最小距离"),
        ),
        migrations.AlterField(
            model_name="job",
            name="sec_distance",
            field=models.FloatField(null=True, verbose_name="第二距离"),
        ),
        migrations.AlterModelTable(name="job", table="job",),
        migrations.AlterModelTable(name="renting", table="renting",),
    ]
