# Generated by Django 4.2 on 2023-05-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendApp", "0002_alter_job_min_distance_alter_job_sec_distance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=14,
                max_digits=18,
                null=True,
                verbose_name="纬度值",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=14,
                max_digits=18,
                null=True,
                verbose_name="经度值",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="min_distance",
            field=models.FloatField(blank=True, null=True, verbose_name="最小距离"),
        ),
        migrations.AlterField(
            model_name="job",
            name="min_house_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="最小距离房子的id"),
        ),
        migrations.AlterField(
            model_name="job",
            name="sec_distance",
            field=models.FloatField(blank=True, null=True, verbose_name="第二距离"),
        ),
        migrations.AlterField(
            model_name="job",
            name="sec_house_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="第二距离房子的id"),
        ),
    ]
